#!/bin/bash
# Copyright (c) 2020 Polyverse Corporation

sed -i '/^PHP_EXTRA_VERSION/s/"$/-poly"/' configure configure.ac Makefile
sed -i '/PHP_EXTRA_VERSION/s/""/"-poly"/' main/php_version.h
sed -i '/PHP_VERSION "/s/"$/-poly"/' main/php_version.h

make -j "$(nproc)"
make install

rm "$POLYSCRIPT_PATH"/polyscript-enable

